import { DEFAULT_MATERIAL, type ThemeSpec } from './spec'

/**
 * Themes that ship with Apiary. They are ordinary specs — validated like any other — and they are
 * written to pass that validation untouched, because they double as the examples the theme
 * generator is shown: whatever they do is what Claude will learn a good theme looks like.
 */
export const BUILTIN_THEMES: ReadonlyArray<{ id: `builtin:${string}`; spec: ThemeSpec }> = [
  {
    id: 'builtin:matrix',
    spec: {
      version: 1,
      name: 'Matrix',
      palette: {
        'bg-window': '#000000ff',
        'bg': '#020b05ff',
        'bg-panel': '#03140ad9',
        'bg-terminal': '#010703ff',
        'border': '#0f4d24ff',
        'text': '#b8ffc4ff',
        'muted': '#4fbf6aff',
        'accent': '#22ff5aff',
        'accent-contrast': '#001a07ff',
        'selected': '#073d18ff',
        'hover': '#0a5a2340',
        'control-bg': '#052610e6',
        'field-bg': '#010703ff',
        'success': '#22ff5aff',
        'info': '#5dffb0ff',
        'warning': '#d6ff4dff',
        'danger': '#ff6b5aff',
        'mr-merged': '#9dffc9ff',
        'handle-color': '#22ff5a66',
        'handle-color-active': '#22ff5aff',
      },
      terminal: {
        foreground: '#b8ffc4ff', background: '#010703ff', cursor: '#22ff5aff', selection: '#0a5a23ff',
        black: '#010703ff', red: '#ff6b5aff', green: '#22ff5aff', yellow: '#d6ff4dff',
        blue: '#3fd98aff', magenta: '#7dffb3ff', cyan: '#5dffb0ff', white: '#b8ffc4ff',
        brightBlack: '#2e7a45ff', brightRed: '#ff9486ff', brightGreen: '#7dff9eff', brightYellow: '#ecff94ff',
        brightBlue: '#7df0b8ff', brightMagenta: '#b3ffd4ff', brightCyan: '#a3ffd6ff', brightWhite: '#effff2ff',
      },
      shape: { radius: 4, gap: 6, density: 'normal' },
      font: { ui: 'space-grotesk', mono: 'share-tech-mono' },
      effects: [
        { kind: 'digital-rain', color: 'accent', intensity: 0.8, speed: 0.5, density: 0.6 },
        { kind: 'scanlines', color: 'bg-window', intensity: 0.6, speed: 0.2, density: 0.5 },
      ],
      material: { ...DEFAULT_MATERIAL },
    },
  },
  {
    id: 'builtin:neon',
    spec: {
      version: 1,
      name: 'Neon cyberpunk',
      palette: {
        'bg-window': '#07011aff',
        'bg': '#0d0221ff',
        'bg-panel': '#1a0b3ad9',
        'bg-terminal': '#0a0119ff',
        'border': '#3b1f6bff',
        'text': '#f5e9ffff',
        'muted': '#b69be0ff',
        'accent': '#ff2a6dff',
        'accent-contrast': '#12001aff',
        'selected': '#2d1459ff',
        'hover': '#ff2a6d26',
        'control-bg': '#24104ae6',
        'field-bg': '#0a0119ff',
        'info': '#05d9e8ff',
        'success': '#39ff9fff',
        'warning': '#ffd319ff',
        'danger': '#ff5f7eff',
        'mr-merged': '#c77dffff',
        'handle-color': '#05d9e866',
        'handle-color-active': '#ff2a6dff',
      },
      terminal: {
        foreground: '#f5e9ffff', background: '#0a0119ff', cursor: '#ff2a6dff', selection: '#3b1f6bff',
        black: '#0a0119ff', red: '#ff2a6dff', green: '#39ff9fff', yellow: '#ffd319ff',
        blue: '#3d8bffff', magenta: '#d16bffff', cyan: '#05d9e8ff', white: '#e0d4f5ff',
        brightBlack: '#6a55a0ff', brightRed: '#ff6b9aff', brightGreen: '#7dffc0ff', brightYellow: '#ffe066ff',
        brightBlue: '#7ab0ffff', brightMagenta: '#e5a3ffff', brightCyan: '#6ff3ffff', brightWhite: '#ffffffff',
      },
      shape: { radius: 10, gap: 8, density: 'normal' },
      font: { ui: 'orbitron', mono: 'jetbrains-mono' },
      effects: [
        { kind: 'perspective-grid', color: 'info', intensity: 0.7, speed: 0.4, density: 0.5 },
        { kind: 'neon-glow', color: 'accent', intensity: 0.5, speed: 0, density: 0 },
        { kind: 'scanlines', color: 'bg-window', intensity: 0.4, speed: 0.2, density: 0.4 },
      ],
      material: { ...DEFAULT_MATERIAL },
    },
  },
  {
    id: 'builtin:paper',
    spec: {
      version: 1,
      name: 'Paper',
      palette: {
        'bg-window': '#e6dfcfff',
        'bg': '#faf6edff',
        'bg-panel': '#f1ebdfff',
        'bg-terminal': '#fbf8f1ff',
        'bg-overlay': '#2b262033',
        'border': '#d6ccb8ff',
        'text': '#2b2620ff',
        'muted': '#6f6557ff',
        'accent': '#a8471fff',
        'accent-contrast': '#fffaf0ff',
        'selected': '#e4dac7ff',
        'hover': '#2b262014',
        'control-bg': '#fbf8f1ff',
        'field-bg': '#fffdf8ff',
        'danger': '#b3261eff',
        'danger-soft': '#b3261e1f',
        'danger-bg': '#f6dcd8ff',
        'success': '#2f7a3aff',
        'warning': '#8a6200ff',
        'info': '#1f5fa8ff',
        'mr-merged': '#6b3fa8ff',
        'scrollbar-thumb': '#6f655766',
        'scrollbar-thumb-hover': '#6f6557aa',
        'handle-color': '#6f655766',
        'handle-color-active': '#a8471fff',
      },
      terminal: {
        foreground: '#2b2620ff', background: '#fbf8f1ff', cursor: '#a8471fff', selection: '#e4dac7ff',
        black: '#2b2620ff', red: '#b3261eff', green: '#2f7a3aff', yellow: '#8a6200ff',
        blue: '#1f5fa8ff', magenta: '#6b3fa8ff', cyan: '#1d7373ff', white: '#6f6557ff',
        brightBlack: '#5a5145ff', brightRed: '#d0412fff', brightGreen: '#3f9a4bff', brightYellow: '#a87a00ff',
        brightBlue: '#2f76c4ff', brightMagenta: '#8552c4ff', brightCyan: '#258f8fff', brightWhite: '#2b2620ff',
      },
      shape: { radius: 12, gap: 8, density: 'roomy' },
      font: { ui: 'ibm-plex-sans', mono: 'ibm-plex-mono' },
      effects: [
        { kind: 'paper-grain', color: 'text', intensity: 0.8, speed: 0, density: 0.6 },
      ],
      material: { ...DEFAULT_MATERIAL },
    },
  },
  {
    id: 'builtin:glass',
    spec: {
      version: 1,
      name: 'Liquid Glass',
      palette: {
        'bg-window': '#0b1026ff',
        'bg': '#10162a80',
        'bg-panel': '#1a203873',
        'bg-terminal': '#0a0e1e99',
        'bg-overlay': '#00000066',
        'border': '#ffffff29',
        'text': '#f4f7ffff',
        'muted': '#c3cce3ff',
        'accent': '#7cc4ffff',
        'accent-contrast': '#06111fff',
        'selected': '#ffffff24',
        'hover': '#ffffff14',
        'control-bg': '#ffffff1f',
        'field-bg': '#0a0e1e73',
        'success': '#7ae8a8ff',
        'warning': '#ffd98aff',
        'danger': '#ff9a9aff',
        'info': '#9ad6ffff',
        'mr-merged': '#d2b6ffff',
        'scrollbar-thumb': '#ffffff40',
        'scrollbar-thumb-hover': '#ffffff73',
        'handle-color': '#ffffff66',
        'handle-color-active': '#7cc4ffff',
      },
      terminal: {
        foreground: '#f4f7ffff', background: '#0a0e1e99', cursor: '#7cc4ffff', selection: '#ffffff33',
      },
      shape: { radius: 14, gap: 10, density: 'normal' },
      font: { ui: 'inter', mono: 'jetbrains-mono' },
      effects: [
        { kind: 'aurora', color: 'accent', intensity: 0.6, speed: 0.3, density: 0.6 },
      ],
      material: { kind: 'glass', blur: 22, saturation: 1.8, highlight: 0.8, refraction: 0.5 },
    },
  },
]
